variables:
  GIT_SUBMODULE_STRATEGY: recursive

mono-module:linux:
  image: hexaflexagon/gtao-mono-ci:latest
  before_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\Tools\VsDevCmd.bat"
  script:
  - msbuild MonoOrange/MonoOrange.vcxproj /t:Rebuild /p:Configuration=Release;Platform=x64
  - (cd MonoOrange && cmake . && make)
  artifacts:
    name: "mono-module-${CI_COMMIT_REF_NAME}-linux64"
    paths:
      - MonoOrange.so
      - MonoOrange
  only:
  - tags