variables:
  GIT_SUBMODULE_STRATEGY: recursive

mono-module:windows:
    before_script:
        - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\Common7\Tools\VsDevCmd.bat"
    script:
        - ./build.bat
    artifacts:
        name: "mono-module-${CI_COMMIT_REF_NAME:~0,8%}-win64"
    paths:
        - windows/MonoOrange.dll
        - windows/MonoOrange/SharpOrange.dll
        - windows/MonoOrange/Std-symbols.so
        - windows/MonoOrange/bin/mono-2.0-sgen.dll
    only:
        - tags

mono-module:linux:
    image: hexaflexagon/gtao-mono-ci:latest
    script:
        - ./build.sh
    artifacts:
        name: "mono-module-${CI_COMMIT_REF_NAME:0:8}-linux64"
    paths:
        - linux/MonoOrange.so
        - linux/MonoOrange/SharpOrange.dll
        - linux/MonoOrange/Std-symbols.so
    only:
        - tags