name: "{ff8f00}[FR]{ffffff} Lambda RP"
port: 7788
players: 1000
password: "007"

masterserver: true

gamemode: "Lambda RP"
website: "https://lambdarp.fr/"
language: "French"
description: "LAMBDA ROLEPLAY EST UN SERVEUR FRANÇAIS BASÉ SUR LE JEU GRAND THEFT AUTO V. 
CELUI-CI SE VEUT INNOVANT. PAR LE BIAIS DE NOS COMPÉTENCES NOUS ÉLABORONS 
UNE PLATEFORME DE JEU QUI PERMETTRA À TOUT JOUEUR DE S'Y INTÉGRER ET DE JOUER PLEINEMENT."

resources:
  - Lambda
  - chat