name: "{ff8f00}GTA:Orange{ffffff}Test Server"
port: 7788
players: 100
#password: "12345"

masterserver: true

gamemode: "Dev"
website: "http://www.google.com/"
language: "English"
description: "Awesome GTA:Orange Server"

resources:
  - chat