//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class API : APIBase {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal API(global::System.IntPtr cPtr, bool cMemoryOwn) : base(OrangeDotNETModulePINVOKE.API_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(API obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~API() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          OrangeDotNETModulePINVOKE.delete_API(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public static API instance {
    set {
      OrangeDotNETModulePINVOKE.API_instance_set(API.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = OrangeDotNETModulePINVOKE.API_instance_get();
      API ret = (cPtr == global::System.IntPtr.Zero) ? null : new API(cPtr, false);
      return ret;
    } 
  }

  public static void Set(API api) {
    OrangeDotNETModulePINVOKE.API_Set(API.getCPtr(api));
  }

  public static API Get() {
    API ret = new API(OrangeDotNETModulePINVOKE.API_Get(), false);
    return ret;
  }

}
