//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class OrangeDotNETModule {
  public static void vmul_sse(SWIGTYPE_p_float a, float b, SWIGTYPE_p_float r) {
    OrangeDotNETModulePINVOKE.vmul_sse(SWIGTYPE_p_float.getCPtr(a), b, SWIGTYPE_p_float.getCPtr(r));
  }

  public static void vdiv_sse(SWIGTYPE_p_float a, float b, SWIGTYPE_p_float r) {
    OrangeDotNETModulePINVOKE.vdiv_sse(SWIGTYPE_p_float.getCPtr(a), b, SWIGTYPE_p_float.getCPtr(r));
  }

  public static void vadd_sse(SWIGTYPE_p_float a, SWIGTYPE_p_float b, SWIGTYPE_p_float r) {
    OrangeDotNETModulePINVOKE.vadd_sse(SWIGTYPE_p_float.getCPtr(a), SWIGTYPE_p_float.getCPtr(b), SWIGTYPE_p_float.getCPtr(r));
  }

  public static void vsub_sse(SWIGTYPE_p_float a, SWIGTYPE_p_float b, SWIGTYPE_p_float r) {
    OrangeDotNETModulePINVOKE.vsub_sse(SWIGTYPE_p_float.getCPtr(a), SWIGTYPE_p_float.getCPtr(b), SWIGTYPE_p_float.getCPtr(r));
  }

  public static void vmodmul_sse(SWIGTYPE_p_float a, SWIGTYPE_p_float b, SWIGTYPE_p_float r) {
    OrangeDotNETModulePINVOKE.vmodmul_sse(SWIGTYPE_p_float.getCPtr(a), SWIGTYPE_p_float.getCPtr(b), SWIGTYPE_p_float.getCPtr(r));
  }

  public static void vclamp_sse(SWIGTYPE_p_float a, SWIGTYPE_p_float min, SWIGTYPE_p_float max, SWIGTYPE_p_float r) {
    OrangeDotNETModulePINVOKE.vclamp_sse(SWIGTYPE_p_float.getCPtr(a), SWIGTYPE_p_float.getCPtr(min), SWIGTYPE_p_float.getCPtr(max), SWIGTYPE_p_float.getCPtr(r));
  }

  public static readonly int M_STRING = OrangeDotNETModulePINVOKE.M_STRING_get();
  public static readonly int M_INT = OrangeDotNETModulePINVOKE.M_INT_get();
  public static readonly int M_BOOL = OrangeDotNETModulePINVOKE.M_BOOL_get();
  public static readonly int M_DOUBLE = OrangeDotNETModulePINVOKE.M_DOUBLE_get();
  public static readonly int M_ULONG = OrangeDotNETModulePINVOKE.M_ULONG_get();
  public static readonly int M_ARRAY = OrangeDotNETModulePINVOKE.M_ARRAY_get();

}
